### ISSUE TITLE
Is it possible to schedule a notification?

### ISSUE THREAD

**Issue by jameslavery** [bytefish/FcmSharp#56]
We need to schedule a notification to be delivered at a particular date/time. Is this possible with FcmSharp?

I have a feeling it isn't because I haven't seen mention of the ability to schedule Notifications via  the FCM API. Am I right?

**Comment by bytefish** [comment]
No, not directly. I have added a sample application, that shows how to add the functionality yourself.

The application creates a Table ``message``:

![image](https://user-images.githubusercontent.com/239373/52885704-68745d00-3172-11e9-87a7-f8ae57a0c69d.png)

This table is checked in an interval for scheduled messages, that need to be sent.

**Comment by bytefish** [comment]
@jameslavery I also added a Quartz.NET-based implementation here:

* https://github.com/bytefish/FcmSharp/tree/master/FcmSharp/Examples/CSharp/FcmSharp.Scheduler.Quartz

It allows to schedule messages at a given time and uses Quartz.NET to schedule it:

![image](https://user-images.githubusercontent.com/239373/52911480-a5d90780-32a4-11e9-9d58-ac59bcd1c350.png)

I wrote it, because I need some scheduling in almost every project and this way I can just copy and paste from this project. 👍

**Comment by jameslavery** [comment]
Thanks! I'll take a look when I'm back at the client on Tuesday.

Sent from my phone. Apologies for brevity and possible auto-correct quirks.

________________________________
