### ISSUE TITLE
Create settings (credentials) via parameter

### ISSUE THREAD

**Issue by EnricoWuestenberg** [bytefish/FcmSharp#60]
The only way to load credentials is via file. Blank files are a security issue. 
I use a deployment pipeline and need to replace variables. 

Something like FileBasedFcmClientSettings.Create(FcmClientSettingsConfig config) would be nice.

![grafik](https://user-images.githubusercontent.com/32926746/55714527-22f64280-59f3-11e9-9717-93f46630c9d1.png)

**Comment by bytefish** [comment]
Can you give me an example? The ``FileBasedFcmClientSettings`` is just a class with static helper methods. You can easily create your own helper methods to generate the credentials. There is also a ``StreamBasedFcmClientSettings`` to create the credentials from a Stream for example:

* https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/FcmSharp/Settings/StreamBasedFcmClientSettings.cs

**Comment by bytefish** [comment]
Please implement the methods you need to safely load the credentials in your applications code. You say "blank files are a security issue", but I fail to see how you can load empty files, because an exception will be thrown:

* https://github.com/bytefish/FcmSharp/blob/master/FcmSharp/FcmSharp/Settings/FileBasedFcmClientSettings.cs#L60

As you can see, the ``FileBasedFcmClientSettings`` and ``StreamBasedFcmClientSettings`` are no magic, so it will be easy to adapt it to your needs.
